#The pyramid
print("          ^           ")
print("         / \          ")
print("        /   \         ")
print("       /     \        ")
print("      /       \       ")
print("     /         \      ")
print("    /           \     ")
print("   /             \    ")
print("  /_______________\   ")
